/-
  E5 · The five-qubit code
  ========================

  The smallest code that corrects any single-qubit error: [[5, 1, 3]]. Its
  stabilizer is generated by XZZXI and its three cyclic shifts. Every generator
  mixes X and Z, so this is not a CSS code.

  Build it the way the demo built Steane: the four literals, the list, then the
  fields of the code. Replace every `sorry`.

  LEMMAS FOR THIS FILE
    GeneratorsIndependent_of_rowsLinearIndependent
    negIdentity_not_mem_of_indep_phase_zero_commute
-/
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerCode
import QEC.Stabilizer.Framework.Symplectic.SymplecticSpan
import QEC.Stabilizer.Foundations.PauliGroup.Notation
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrixDecidable
import QEC.Stabilizer.Codes.Small.FiveQubit_5_1_3
import QECWidgets.CheckMatrix

open Quantum Quantum.StabilizerGroup NQubitPauliGroupElement
open scoped Pauli

namespace E5

/-  1 · Generators  -/

/-
  g1 = X Z Z X I
  g2 = I X Z Z X
  g3 = X I X Z Z
  g4 = Z X I X Z
-/
def g1 : NQubitPauliGroupElement 5 := sorry
def g2 : NQubitPauliGroupElement 5 := sorry
def g3 : NQubitPauliGroupElement 5 := sorry
def g4 : NQubitPauliGroupElement 5 := sorry

def gens : List (NQubitPauliGroupElement 5) := [g1, g2, g3, g4]

-- Once the literals are in, uncomment and put the cursor on the line: the check
-- matrix, and whether every pair commutes.
-- #check_matrix gens

/-  2 · The code  -/

def fiveQubit : StabilizerCode 5 1 := sorry

/-  3 · Bonus: the distance  -/

-- QECLean proves distance 3 for its own copy of this code,
-- `FiveQubit_5_1_3.code_has_distance_three`. State `HasCodeDistance fiveQubit 3`,
-- unfold `HasCodeDistance` once and read the three clauses, then see whether the
-- library's proof applies to yours.

end E5
